### ISSUE TITLE
"Warning: 'assert' redefined" when using glibc's assert.h

### ISSUE THREAD

**Issue by mariusor** [mortie/snow#13]
Hi, I'm trying to use snow in an existing code-base which uses asserts in various parts. Is there something I can do to avoid these types of warnings?

```
In file included from ../test.c:7:0:
.././lib/snow/snow/snow.h:172:0: warning: "assert" redefined
 #define assert(x) \
 
In file included from ../../src/utils.h:9:0,
                 from ../test.c:6:
/usr/include/assert.h:104:0: note: this is the location of the previous definition
```

BTW, I'm compiling using meson/ninja's test functionality.

**Comment by mortie** [comment]
You can put `#undef assert` before including `snow.h`. Snow should probably do that automatically.

**Comment by mortie** [comment]
https://github.com/mortie/snow/commit/aabd97a10cd39e7710e84272fc150368a3d44f27 fixes this.
