### ISSUE TITLE
Compiling with -Wpedantic triggers warnings

### ISSUE THREAD

**Issue by mariusor** [mortie/snow#18]
I'm not sure if it's reasonable to ask this, but I usually compile my projects using `-Wpedantic` (I'm not a very experienced C developer) so every bit of help in avoiding issues is good for me. 

When I test my program using snow, the compiler throws a lot of warnings. 

I looked them over trying to come up with a PR, but unfortunatelly the code goes over my head and I can't come up with something helpful which wouldn't break or would make sense. 

To test you can just add `-Wpedantic` to the example project's Makefile.

Is it possible to change the code to quiet all these warnings, or compiling with this flag should be out of the question?

**Comment by mortie** [comment]
The `-Wpedantic` flag makes the compiler issue warnings when it encounters non-standard features; features which the compiler has, but which isn't part of the ISO C standard and isn't guaranteed to compile with all standards compliant C compilers. Snow uses a few such features, so GCC is completely correct to issue warnings when compiling with `-Wpedantic`. I don't think it's practical to remove all uses of non-standard features from Snow.

However, it would be possible for Snow to disable the `-Wpedantic` warnings, ironically using the non-standard pragma `#pragma GCC diagnostic ignored "-Wpedantic"`. That would mean that all the code until `#include <snow/snow.h>`, which should be all your non-testing code, would be compiled with `-Wpedantic`, while all the testing code would compile without pedantic warnings. I don't know if I love the idea of disabling specific warnings which the user purposefully added, but I do something similar with `-Wint-conversion` for the assertneq and asserteq macros, where pointers might get implicitly casted to `intmax_t`.

I will come back to this in a bit after discussing it with people, but I do see the value in compiling your test suite with strict warnings (and even with `-Werror` to make the test suite fail if there are warnings), and making everything after `#include <snow/snow.h>` ignore pedantic warnings would make that easier.

**Comment by mariusor** [comment]
I think in this case is easier for the user to compile tests without -Wpedantic and just use it for regular compiles. 

I think the only thing to be done is to document this in the README.

**Comment by mortie** [comment]
After way too long, I've finally done something about this - https://github.com/mortie/snow/commit/bb81c83b52f718c6e4f13d277cbc48e4a6b7dcc5. I will release version 1.5.0 with that change soon.

The reason I've kept this open is that I really want to be able to compile my tests with as strict warnings as possible, and make the test suite fail if there are any warnings.

**Comment by mariusor** [comment]
Hey @mortie. I'm glad you worked it out in the end. Thank you.

I'll let you know if I stumble on any issues. :P
