### ISSUE TITLE
Implicit declaration of function ‘_Generic’ for older gcc versions

### ISSUE THREAD

**Issue by timgabets** [mortie/snow#4]
Hi, it seems that the library is not gonna work with some old GCC versions. For example, I tred to use it with gcc v4.1.2 and received this:

`conv_utils_suite.c:4: warning: implicit declaration of function ‘_Generic’`

**Comment by mortie** [comment]
The _Generic keyword is from c11. It looks like GCC added support for it in GCC 4.9.

If you're not able to upgrade your compiler, you can use the `asserteq_{str,int,ptr}` macros instead of the `asserteq` macro, because the explicit macros don't depend on _Generic.

**Comment by mortie** [comment]
I just pushed a commit https://github.com/mortie/snow/commit/36a71d7f09027e2440df64e02c40658ffb83e3ab which makes the compiler produce a better error message when trying to use `asserteq` and `assertneq` with a compiler which doesn't support C11.
